import { StyleSheet, Dimensions } from 'react-native';

const { width } = Dimensions.get('window');

export const styles = StyleSheet.create({
  overlay: {
    position: 'absolute',
    top: 0,
    bottom: 0,
    width: width,
    zIndex: 100,
    flexDirection: 'row',
    fontFamily: 'Jua_400Regular',
  },
  background: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.2)',
  },
  sidebar: {
    width: width,
    
    backgroundColor: '#F5F5F5',
    paddingTop: 40,
    paddingHorizontal: 20,
    borderTopLeftRadius: 20,
    borderBottomLeftRadius: 20,
    shadowColor: '#000',
    shadowOffset: { width: -2, height: 0 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 10,
    position: 'relative',
    fontFamily: 'Jua_400Regular',
  },
  topCard: {
    backgroundColor: '#fff',
    borderRadius: 12,
    padding: 16,
    marginBottom: 10,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 4,
    elevation: 2,
    fontFamily: 'Jua_400Regular',
  },
  topTitle: {
    fontSize: 16,
    color: '#333',
    fontFamily: 'Jua_400Regular',
  },
  topSubtitle: {
    fontSize: 13,
    color: '#666',
    marginTop: 2,
    fontFamily: 'Jua_400Regular',
  },
  topButton: {
    backgroundColor: '#7B3FA0',
    borderRadius: 8,
    paddingVertical: 6,
    paddingHorizontal: 16,
    marginLeft: 10,
    fontFamily: 'Jua_400Regular',
  },
  topButtonText: {
    color: '#fff',
    fontSize: 14,
    fontFamily: 'Jua_400Regular',
  },
  sectionTitle: {
    marginTop: 2,
    marginBottom: 2,
    color: '#444',
    fontSize: 15,
    fontFamily: 'Jua_400Regular',
  },
  itemRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 10,
    gap: 12,
    fontFamily: 'Jua_400Regular',
  },
  itemLabel: {
    fontSize: 15,
    color: '#7B3FA0',
    marginLeft: 8,
    fontFamily: 'Jua_400Regular',
  },
  closeButton: {
    position: 'absolute',
    bottom: 30,
    right: 30,
    backgroundColor: '#fff',
    borderRadius: 20,
    width: 40,
    height: 40,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
    fontFamily: 'Jua_400Regular',
  },
  closeButtonText: {
    fontSize: 28,
    color: '#7B3FA0',
    marginTop: -2,
    fontFamily: 'Jua_400Regular',
  },
});
