import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
    bg: {
      flex: 1,
      width: '100%',
      height: '105%',
      justifyContent: 'center',
      alignItems: 'center',
    },
    container: {
      alignItems: 'center',
      justifyContent: 'center',
      marginTop: 40,
    },
    paws: {
      margin: 'auto',
      position: 'static',
    },
    title: {
      fontSize: 28,
      color: '#7B3FA0',
      fontFamily: 'Jua_400Regular',
    },
    form: {
      backgroundColor: '#E5E5E5',
      borderRadius: 18,
      padding: 24,
      width: 320,
      alignItems: 'center',
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.08,
      shadowRadius: 8,
      elevation: 3,
    },
    label: {
      fontSize: 15,
      color: '#7B3FA0',
      alignSelf: 'flex-start',
      marginTop: 10,
      marginBottom: 4,
      marginLeft: 12,
      fontFamily: 'Jua_400Regular',
    },
    input: {
      width: '100%',
      height: 40,
      backgroundColor: '#fff',
      borderRadius: 6,
      paddingHorizontal: 12,
      fontSize: 16,
      marginBottom: 8,
      borderWidth: 0,
      fontFamily: 'Jua_400Regular',
    },
    linksRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      width: '100%',
      marginBottom: 18,
      marginTop: 2,
    },
    link: {
      color: '#7B3FA0',
      fontSize: 14,
      textDecorationLine: 'underline',
      textDecorationColor: 'transparent',
      fontFamily: 'Jua_400Regular',
    },
    button: {
      backgroundColor: '#7B3FA0',
      borderRadius: 8,
      paddingVertical: 8,
      alignItems: 'center',
      marginTop: 8,
      width: '80%',
    },
    buttonText: {
      color: '#fff',
      fontSize: 15,
      letterSpacing: 1,
      fontFamily: 'Jua_400Regular',
    },
  });