import { StyleSheet } from "react-native";
import { colors } from "@/styles/colors";

export const styles = StyleSheet.create({
    card: {
        backgroundColor: colors.white,
        borderRadius: 16,
        padding: 16,
        width: '90%',
        position: 'relative',
        marginTop: 20,
        marginHorizontal: 'auto',
        borderWidth: 1,
        borderColor: colors.gray[200],
        shadowColor: colors.gray[900],
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.05,
        shadowRadius: 8,
        elevation: 2,
    },
    slideContainer: {
        flexGrow: 0,
        paddingHorizontal: 10,
        marginVertical: 8,
    },
    row: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        marginBottom: 16,
    },
    title: {
        fontSize: 24,
        color: colors.purple[700],
        fontFamily: 'Jua_400Regular',
        marginLeft: 12,
    },
    avatarContainer: {
        borderWidth: 2,
        borderColor: colors.purple[400],
        borderRadius: 40,
        padding: 2,
        marginRight: 16,
        backgroundColor: colors.white,
        shadowColor: colors.purple[600],
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 1,
    },
    avatar: {
        width: 56,
        height: 56,
        borderRadius: 28,
    },
    nome: {
        fontSize: 20,
        color: colors.purple[700],
        fontFamily: 'Jua_400Regular',
        marginBottom: 4,
    },
    status: {
        color: colors.gray[600],
        fontSize: 14,
        fontFamily: 'Jua_400Regular',
    },
    iconsRow: {
        flexDirection: 'row',
        justifyContent: 'space-around',
        marginTop: 16,
        paddingTop: 16,
        borderTopWidth: 1,
        borderTopColor: colors.gray[200],
        paddingHorizontal: 16,
    },
    iconButton: {
        backgroundColor: colors.gray[200],
        borderRadius: 12,
        alignItems: 'center',
        justifyContent: 'center',
        width: 48,
        height: 48,
    },
    emptyContainer: {
        alignItems: 'center',
        justifyContent: 'center',
        paddingVertical: 32,
        backgroundColor: colors.white,
        borderRadius: 16,
        borderWidth: 2,
        borderColor: colors.purple[400],
        borderStyle: 'dashed',
    },
    emptyText: {
        fontSize: 16,
        color: colors.purple[600],
        marginBottom: 16,
        textAlign: 'center',
        fontFamily: 'Jua_400Regular',
    },
    cadastroButton: {
        backgroundColor: colors.purple[600],
        borderRadius: 12,
        paddingVertical: 12,
        paddingHorizontal: 32,
        alignItems: 'center',
        shadowColor: colors.purple[600],
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.15,
        shadowRadius: 6,
        elevation: 2,
    },
    cadastroButtonText: {
        color: colors.white,
        fontSize: 16,
        fontFamily: 'Jua_400Regular',
    },
});